[entryPoints]
  [entryPoints.http]
    address = ":80"
  [entryPoints.https]
    address = ":443"

[api]

[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

[http]
  [http.services]
    [http.services.inventaireDB]
      [http.services.inventaireDB.loadBalancer]
        [[http.services.inventaireDB.loadBalancer.servers]]
          url = "http://$PRIVATE_IP/"
